### ISSUE TITLE
Front end minor issues

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer-backend#15]
Visualization typos in front end tooltips
snapshoot -> snapshot
record -> Record (if you care about consistency)
Model info. -> remove period; also the fields are empty when you click on it

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Can you take care of the first two issues above? Also the size of the rectangle of the drop area for drag-and-drop is a bit skinny, could that be enlarged a bit? Thank you

**Comment by aymanhab** [comment]
I fixed the typos in the i18n file.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab , I enlarged the drop area and pushed to dev, increasing padding from 16 to 50 in the vertical axis.

**Comment by aymanhab** [comment]
This seems to have been fixed, will move to done pending feedback.
